services:
  bookstack:
    image: solidnerd/bookstack:latest
    container_name: bookstack
    environment:
      - APP_URL=http://localhost
      - DB_HOST=db:3306
      - DB_DATABASE=bookstack
      - DB_USERNAME=bookstackuser
      - DB_PASSWORD=secretpassword
      - DB_CONNECTION=mysql
      - APP_KEY=base64:$(php -r "echo base64_encode(random_bytes(32));")
    ports:
      - "80:80"       # HTTP for web access
    volumes:
      - ./bookstack/uploads:/var/www/bookstack/public/uploads  # Persist file uploads
      - ./bookstack/storage:/var/www/bookstack/storage  # Persist app data
    depends_on:
      - db
    networks:
      - bookstack_network
    restart: always

  db:
    image: mysql:5.7
    container_name: bookstack-db
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=bookstack
      - MYSQL_USER=bookstackuser
      - MYSQL_PASSWORD=secretpassword
    volumes:
      - ./bookstack/db:/var/lib/mysql  # Persist MySQL data
    networks:
      - bookstack_network
    restart: always

networks:
  bookstack_network:
    driver: bridge

volumes:
  bookstack_db:
  bookstack_storage:
