services:
  ubuntu:
    image: ubuntu:24.04
    container_name: ubuntu-container
    stdin_open: true    # Keeps the container open for interactive use
    tty: true           # Allocates a pseudo-TTY, useful for interactive use
    command: sleep infinity # Keeps the container running indefinitely
    volumes:
      - ./data:/data    # Optional: You can mount a volume if you want to persist data
    networks:
      - ubuntu_network
    restart: always

networks:
  ubuntu_network:
    driver: bridge